# Generated by Django 4.2.7 on 2025-11-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_members',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks_many', to='teams.membership'),
        ),
    ]
